
### load config file and set working directory ###
configfile: "config.yaml"

include: "rules/common.smk" 
include: "rules/quant.smk"
include: "rules/pizzly.smk"
include: "rules/merge.smk"
include: "rules/requant.smk"
include: "rules/sleuth.smk"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

# The first rule should define the default target files
# Subsequent target rules can be specified below. They should start with all_*.
rule all:
    input:
        # kallisto fusion output per sample
        expand("kallisto/quant/{reference}/{sample}/abundance.tsv", 
        reference=REFERENCE, sample=samples['sample']),

        # pizzly fusion fasta output per sample
        expand([
            "pizzly/fusion/{reference}/{sample}/output.fusions.fasta", 
            "pizzly/fusion/{reference}/{sample}/genetable.tsv"], 
            reference=REFERENCE, sample=samples['sample']),

        # reference t2g
        T2G,

        # merged fusion fasta
        expand([
            "pizzly/merge/{reference}/{project}/summary.txt",
            "pizzly/merge/{reference}/{project}/transcripts_with_fusions.idx",
            "pizzly/merge/{reference}/{project}/output.fusions.combined.unique.filtered.fasta",
            "pizzly/merge/{reference}/{project}/fusions_t2g.tsv", 
            "pizzly/merge/{reference}/{project}/combined_t2g.tsv"],
            reference=REFERENCE, project=PROJECT),

        # kallisto requant output per sample
        expand("kallisto/requant/{reference}/{sample}/{project}/abundance.tsv", 
            reference=REFERENCE, sample=samples['sample'], project=PROJECT),

        # sleuth set up
        expand("sleuth/{reference}/{project}/samplesheet.tsv", 
            reference=REFERENCE, project=PROJECT),
        expand("sleuth/{reference}/{project}/h5_status.txt", 
            reference=REFERENCE, project=PROJECT)
